# Generated by Django 5.1.6 on 2025-04-04 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agendamentos', '0001_initial'),
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicoUsuario', to='Service.servico'),
        ),
    ]
